# ─────────────────────────────────────────
# API — ASP.NET Core 10 - PRODUCTION
# ─────────────────────────────────────────
version: '3.9'

services:
  admin-tickets:
    container_name: admin-tickets

    build:
      context: .
      dockerfile: Dockerfile

    image: admin-tickets:latest

    ports:
      - "5202:8080"

    restart: unless-stopped
    
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ApiBaseUrl: "https://api.kepler.andrescortes.dev"


